# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Proportions Don't Matter"
tagline:          "Recipes are made up, and the proportions don't matter"
description:      'Made by typeundeclared.'
url:              https://typeundeclared.github.io/
baseurl:          ""

author:
  name:           typeundeclared
  url:            typeundeclared.github.io

paginate:         5

gems:
   - jekyll-paginate
