# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Proportions Don't Matter"
tagline:          "Recipes are made up, and the proportions don't matter"
description:      'Made by typeundeclared.'
url:              https://github.com/typeundeclared/typeundeclared
baseurl:          /

author:
  name:           typeundeclared
  url:            typeundeclared.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/typeundeclared/typeundeclared
